name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  deploy:
    name: 'Deploy'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: jsmrcaga/action-netlify-deploy@v1.8.0
        with:
          NETLIFY_AUTH_TOKEN: BqVbEiLU6h4ZfDZ_OC9Lf0SCc-0feLO_CSfdgz8G4JQ
          NETLIFY_SITE_ID: BiMEBOFZc4m7ESP-qT__HjtiM9xMp9f1pA_NLWL5yqg
          NETLIFY_DEPLOY_TO_PROD: true
          build_command: npm run build
          
        
