name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: [ "main" ]
    
env:
  ARTIFACT_NAME: react-app
    
jobs:
  build:
    name: 'Build React App'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Sources'
        uses: actions/checkout@v2.4.2
        
      - name: 'Install Dependencies'
        run: npm install
        working-directory: ./learning-react
        
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npx playwright test
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
        
      - name: 'Build Application'
        run: |
          npm run build
        working-directory: ./learning-react
      - name: Publish Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{env.ARTIFACT_NAME}}
          path: ./learning-react/build
          
  deploy:
    name: 'Deploy'
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{env.ARTIFACT_NAME}}
          path: ${{env.ARTIFACT_NAME}}
      
      - name: List files after artifact download
        run: |
          ls ${{github.workspace}} -la
        
      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v1.2
        with:
          publish-dir:  '${{github.workspace}}/${{env.ARTIFACT_NAME}}'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Deploy from GitHub Actions ${{ github.event.pull_request.title }}"  
          production-branch: main
          
          enable-pull-request-comment: true
          enable-commit-comment: true
          enable-commit-status: true
          overwrites-pull-request-comment: true
          
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1
          
        
