name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  build:
    name: 'Build React App'
    runs-on: ubuntu-latest
    steps:
      - name: NPM Build
        run: npm run build
        working-directory: 'learning-react'
  deploy:
    name: 'Deploy'
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v1.2
        with:
          publish-dir: './learning-react/build'
          deploy-message: "Deploy from GitHub Actions"
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1
          
        
